name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: username
    attributes:
      label: @ no Github
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Time
      description: What version of our software are you running?
      options:
        - pybr2024-org
        - pybr2023-org
        - pybr2023-org
    validations:
      required: true
