# This workflow uses actions that are not certified by GitHub.
# São fornecidas por terceiros e regidas por
# termos de serviço, política de privacidade e suporte separados
# documentação.

name: Boletim

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
    steps:
      - name: Get issue template
        uses: imjohnbo/extract-issue-template-fields@v0.0.1
        id: template
        with:
          path: .github/ISSUE_TEMPLATE/boletim.md

      - name: Define title and assignee
        id: script
        run: |
          # Define issue title
          LANG=pt_BR
          month=$(date +%B)
          year=$(date +%Y)
          title="Boletim Informativo de $month de $year"
          echo "::set-output name=title::$title"
          
          # Define issue assignee
          assignees[0]="rougeth"  # tiidadavena
          assignees[1]="rougeth"  # muriloviana
          assignees[2]="rougeth"
          assignees[3]="rougeth"  # anadulce

          month=$(date +%m)
          size=${#assignees[@]}
          index=$(($month % $size))
          echo "::set-output name=assignee::${assignees[$index]}"

      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: ${{ steps.script.outputs.assignee }}
          labels: ${{ steps.template.outputs.labels }}
          title: ${{ steps.script.outputs.title }}
          body: ${{ steps.template.outputs.body }}
