on: workflow_dispatch
env:
  LANG: "pt_BR.UTF-8"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pt_BR.UTF-8
      run: |
        sudo locale-gen pt_BR.UTF-8
        sudo update-locale LANG=pt_BR.UTF-8
    - name: date
      run: |
        date
    - name: date2
      run: |
        date +%B

